import type { Metadata } from 'next'
import './globals.css'
import { Raleway, Poppins } from 'next/font/google'

export const raleway = Raleway({
	subsets: ['cyrillic'],
	display: 'swap',
	preload: true,
	weight: 'variable',
})

export const metadata: Metadata = {
	title: 'Busy Bees Addis',
	description: 'Generated by create next app',
}

export const poppins = Poppins({
	subsets: ['latin'],
	weight: '900',
	display: 'swap'
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className='scroll-smooth'>
			<body className={raleway.className}>{children}</body>
		</html>
	)
}
