import type { Metadata } from 'next'
import './globals.css'
import { playfairDisplayItalic, raleway } from '@/styles/fonts'

export const metadata: Metadata = {
	title: 'Busy Bees Addis',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className='scroll-smooth'>
			<body className={playfairDisplayItalic.className}>{children}</body>
		</html>
	)
}
