# Generated by Django 4.1 on 2024-03-31 22:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/')),
                ('hero_image', models.ImageField(upload_to='images/')),
                ('reading_bee_image', models.ImageField(upload_to='images/')),
                ('brand', models.CharField(max_length=255)),
                ('motto', models.CharField(max_length=255)),
                ('section_title', models.CharField(max_length=255)),
                ('program', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypicalDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('activities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=20)),
            ],
        ),
    ]
