# Generated by Django 4.1 on 2024-03-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0002_compoundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='hero_image',
            field=models.ImageField(upload_to='images/hero/'),
        ),
    ]
