# Generated by Django 4.1 on 2024-04-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0003_alter_intro_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundimage',
            name='caption',
            field=models.CharField(default='', max_length=255),
        ),
    ]
