# Generated by Django 4.1 on 2024-04-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0004_compoundimage_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='section_title',
            new_name='program_title',
        ),
    ]
