# Generated by Django 4.1 on 2024-04-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0007_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_house_image', models.ImageField(upload_to='images/open-house/')),
                ('caption', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
