# Generated by Django 4.1 on 2024-04-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0009_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('country', models.CharField(max_length=55)),
                ('phone_number_1', models.CharField(max_length=55)),
                ('phone_number_2', models.CharField(max_length=55)),
                ('phone_number_3', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='images/footer/')),
            ],
        ),
    ]
