# Generated by Django 4.1 on 2024-04-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0010_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='facebook',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='instagram',
            field=models.CharField(default='', max_length=255),
        ),
    ]
