# Generated by Django 4.1 on 2024-04-14 00:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0014_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('hero_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('brand', models.CharField(max_length=255)),
                ('motto', models.CharField(max_length=255)),
            ],
        ),
    ]
