# Generated by Django 4.1 on 2024-04-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0017_program'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.DeleteModel(
            name='Intro',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
