# Generated by Django 4.1 on 2024-04-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0018_delete_example_delete_intro_delete_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypicalDay',
        ),
    ]
