# Generated by Django 4.1 on 2024-04-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0020_typicalday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompoundImage',
        ),
    ]
