# Generated by Django 4.1 on 2024-04-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0022_compoundimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenHouseImage',
        ),
    ]
