# Generated by Django 4.1 on 2024-04-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0024_openhouseimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
