# Generated by Django 4.1 on 2024-04-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0026_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
