# Generated by Django 4.1 on 2024-04-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0028_address_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Contact',
        ),
    ]
